export default {
  LANDINGPAGE: 'landingPage',
  LOGINUSERNAME: 'login',
  LOGINPASSWORD: 'password',
  SIGNUP: 'signup',
  TABROUTES: 'tabroutes',
  HOMESCREEN: 'home',
  ACCOUNT: 'account',
  BAG: 'bag',
  STORES: 'stores',
  WISHLIST: 'wishlist',
  SHOPOPTIONS: 'shopoptions',
  PRODUCTPAGE: 'productpage',
  CHECKOUT: 'checkout',
};
